### ISSUE TITLE
/parkingPose returns wrong block spacing

### ISSUE THREAD

**Issue by elliotwoods** [danftang/KC54#1]
This function reads a pre-rendered json file which seems to have been rendered with the wrong PhysicalProperties (wrong spacing between the blocks).
![image](https://user-images.githubusercontent.com/328294/74904995-78132b00-53f0-11ea-8a03-555f34920d93.png)

**Comment by elliotwoods** [comment]
let's make it do the maths each time.
just in-case we change anything else and dont realise (e.g. a block weights)

**Comment by danftang** [comment]
Just use MinimiseMoments objective
